# Generated by Django 4.0.3 on 2024-02-27 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_app', '0002_remove_userprofile_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('User', 'User'), ('Security', 'Security')], default=0, max_length=10),
            preserve_default=False,
        ),
    ]
