# Generated by Django 4.0.3 on 2024-02-28 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_app', '0003_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='category',
            field=models.CharField(choices=[('Software', 'Software'), ('HR', 'HR'), ('IT', 'IT')], max_length=20),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='department',
            field=models.CharField(choices=[('DevOps', 'DevOps'), ('Python Full Stack', 'Python Full Stack')], max_length=20),
        ),
    ]
