# Generated by Django 4.0.3 on 2024-02-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_app', '0004_alter_visitor_category_alter_visitor_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='pass_type',
            field=models.CharField(choices=[('Single Day', 'Single Day'), ('Multiple Days', 'Multiple Days')], max_length=20, null=True),
        ),
    ]
