# Generated by Django 4.0.3 on 2024-02-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_app', '0005_alter_visitor_pass_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='visitor_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
