# Generated by Django 4.0.3 on 2024-02-28 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_app', '0006_alter_visitor_visitor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='category',
            field=models.CharField(choices=[('Software', 'Software'), ('HR', 'HR'), ('IT', 'IT')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='company_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='department',
            field=models.CharField(choices=[('DevOps', 'DevOps'), ('Python Full Stack', 'Python Full Stack')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='visitor_app.staff'),
        ),
    ]
