# Generated by Django 4.0.3 on 2024-02-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_app', '0007_alter_visitor_category_alter_visitor_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='in_date_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='purpose',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
